stages:
  - build
  - test
  - deploy

# Build Stage - Build the backend project
build_backend:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - mvn clean install -DskipTests=true  # Build the project, skipping tests
  artifacts:
    paths:
      - target/test-classes  # Store any generated test classes or build artifacts (e.g., jar files)
  only:
    - main  # Trigger the build on the main branch

# Test Stage - Run the tests and store the results
test_backend:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - mvn test  # Run the unit tests
  artifacts:
    paths:
      - target/test-classes  # Save test classes (optional)
    reports:
      junit: target/test-classes/*.xml  # Save JUnit test results as reports (GitLab will display these)
  only:
    - main  # Trigger the tests on the main branch

# Deploy Stage - Publish the test results using GitLab Pages
deploy:
  stage: deploy
  script:
    - echo "Deploying test results to GitLab Pages..."
    - mv target/test-classes public/test-results  # Move test results to the public directory
  only:
    - main  # Trigger deploy only on the main branch
  artifacts:
    paths:
      - public  # GitLab Pages expects the content to be in the 'public' directory
  environment:
    name: production
    url: https://NikolaBogosavljevic.gitlab.io/NiBog_M450
  # Replace with your actual GitLab Pages URL
