name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Backend
      run: mvn clean install -DskipTests=true
      working-directory: "Project LB2/recipe-planner-backend"

    - name: Run Tests
      run: mvn test
      continue-on-error: true
      working-directory: "Project LB2/recipe-planner-backend"

    - name: Store Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "Project LB2/recipe-planner-backend/target/test-classes"

    - name: Deploy Test Results to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "Project LB2/recipe-planner-backend/target/test-classes"
        publish_branch: gh-pages

    - name: Clean up
      run: git checkout main
